
import {initializeApp} from "https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import {getAuth,signInWithEmailAndPassword,signOut,onAuthStateChanged} from "https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";
import {getFirestore,collection,addDoc,updateDoc,deleteDoc,doc,query,orderBy,onSnapshot,serverTimestamp} from "https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";
import {firebaseConfig,ADMIN_EMAIL} from "../assets/config.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=s=>document.querySelector(s);
$("#loginForm").addEventListener("submit",async e=>{e.preventDefault();try{const c=await signInWithEmailAndPassword(auth,$("#email").value.trim(),$("#password").value);if(c.user.email!==ADMIN_EMAIL){await signOut(auth);throw 0}}catch{$("#loginStatus").textContent="이메일 또는 비밀번호를 확인해 주세요."}});
$("#logout").addEventListener("click",()=>signOut(auth));
document.querySelectorAll("[data-panel]").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll("[data-panel]").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".panel").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#panel-"+b.dataset.panel).classList.add("active")}));
let started=false;onAuthStateChanged(auth,u=>{const ok=u&&u.email===ADMIN_EMAIL;$("#loginView").classList.toggle("hidden",ok);$("#adminView").classList.toggle("hidden",!ok);if(ok){$("#adminEmail").textContent=u.email;if(!started){started=true;start()}}});
function reset(f){f.reset();f.elements._id.value="";f.querySelector("[data-submit]").textContent="저장";f.querySelector("[data-cancel]").classList.add("hidden")}
function data(f){const o={};for(const[k,v]of new FormData(f)){if(k!="_id")o[k]=v.trim()}if(o.difficulty)o.difficulty=Number(o.difficulty);if("tags"in o)o.tags=o.tags?o.tags.split(",").map(x=>x.trim()).filter(Boolean):[];o.updatedAt=serverTimestamp();return o}
function start(){document.querySelectorAll(".content-form").forEach(f=>{f.addEventListener("submit",async e=>{e.preventDefault();const id=f.elements._id.value,d=data(f);if(id)await updateDoc(doc(db,f.dataset.collection,id),d);else await addDoc(collection(db,f.dataset.collection),{...d,createdAt:serverTimestamp()});reset(f)});f.querySelector("[data-cancel]").addEventListener("click",()=>reset(f))});
["songs","notices","schedules","wardrobe","instagram","curiosity"].forEach(name=>{const el=document.querySelector(`[data-list="${name}"]`);onSnapshot(query(collection(db,name),orderBy("createdAt","desc")),s=>{el.innerHTML=s.empty?'<div class="empty">등록된 내용이 없어요.</div>':s.docs.map(d=>{const x=d.data();return `<div class="manage-row"><div><h3>${x.title||"제목 없음"}${x.artist?" · "+x.artist:""}</h3><p>${x.content||x.date||""}</p></div><div class="mini"><button class="soft" data-edit="${d.id}">수정</button><button class="danger" data-delete="${d.id}">삭제</button></div></div>`}).join("");el.querySelectorAll("[data-delete]").forEach(b=>b.addEventListener("click",async()=>{if(confirm("정말 삭제할까요?"))await deleteDoc(doc(db,name,b.dataset.delete))}));el.querySelectorAll("[data-edit]").forEach(b=>b.addEventListener("click",()=>{const sd=s.docs.find(d=>d.id===b.dataset.edit),x=sd.data(),f=document.querySelector(`form[data-collection="${name}"]`);f.elements._id.value=sd.id;[...f.elements].forEach(e=>{if(!e.name||e.name=="_id")return;e.value=e.name=="tags"?(x.tags||[]).join(", "):(x[e.name]??"")});f.querySelector("[data-submit]").textContent="수정 저장";f.querySelector("[data-cancel]").classList.remove("hidden")}))})})}
