import {initializeApp} from "https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import {getAuth,signInWithEmailAndPassword,signOut,onAuthStateChanged} from "https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";
import {getFirestore,collection,addDoc,updateDoc,deleteDoc,doc,getDoc,setDoc,query,orderBy,onSnapshot,serverTimestamp} from "https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";
import {getStorage,ref,uploadBytes,getDownloadURL} from "https://www.gstatic.com/firebasejs/12.2.1/firebase-storage.js";
import {firebaseConfig,ADMIN_EMAIL} from "../assets/config.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),storage=getStorage(app),$=s=>document.querySelector(s);
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
$("#loginForm").addEventListener("submit",async e=>{e.preventDefault();try{const c=await signInWithEmailAndPassword(auth,$("#email").value.trim(),$("#password").value);if(c.user.email!==ADMIN_EMAIL){await signOut(auth);throw 0}}catch{$("#loginStatus").textContent="이메일 또는 비밀번호를 확인해 주세요."}});
$("#logout").addEventListener("click",()=>signOut(auth));
document.querySelectorAll("[data-panel]").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll("[data-panel]").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".panel").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#panel-"+b.dataset.panel).classList.add("active")}));
let started=false;onAuthStateChanged(auth,u=>{const ok=u&&u.email===ADMIN_EMAIL;$("#loginView").classList.toggle("hidden",ok);$("#adminView").classList.toggle("hidden",!ok);if(ok){$("#adminEmail").textContent=u.email;if(!started){started=true;start()}}});
function preview(f,url){const b=f.querySelector('.image-preview');if(b)b.innerHTML=url?`<img src="${esc(url)}" alt="미리보기" style="max-width:260px;max-height:260px;border-radius:18px;margin-top:10px;object-fit:cover">`:''}
function reset(f){f.reset();if(f.elements._id)f.elements._id.value='';if(f.elements.imageUrl)f.elements.imageUrl.value='';f.querySelector('[data-submit]').textContent='저장';const c=f.querySelector('[data-cancel]');if(c)c.classList.add('hidden');preview(f,'');const s=f.querySelector('.upload-status');if(s)s.textContent=''}
function data(f){const o={};for(const[k,v]of new FormData(f)){if(k!=="_id")o[k]=typeof v==='string'?v.trim():v}if(o.difficulty)o.difficulty=Number(o.difficulty);if('tags'in o)o.tags=o.tags?o.tags.split(',').map(x=>x.trim()).filter(Boolean):[];o.updatedAt=serverTimestamp();return o}
async function uploadImage(f,folder){const file=f.querySelector('.image-file')?.files?.[0];if(!file)return f.elements.imageUrl?.value||'';if(file.size>8*1024*1024)throw new Error('사진은 8MB 이하만 올릴 수 있어요.');if(!['image/png','image/jpeg','image/webp','image/gif'].includes(file.type))throw new Error('PNG, JPG, WEBP, GIF 파일만 올릴 수 있어요.');const st=f.querySelector('.upload-status');if(st)st.textContent='사진 업로드 중...';const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const r=ref(storage,`${folder}/${Date.now()}_${safe}`);await uploadBytes(r,file,{contentType:file.type});const url=await getDownloadURL(r);if(st)st.textContent='사진 업로드 완료!';return url}
async function loadHome(){const f=document.querySelector('.singleton-form'),s=await getDoc(doc(db,'home','main'));if(s.exists()){const x=s.data();for(const e of f.elements)if(e.name&&x[e.name]!==undefined)e.value=x[e.name];preview(f,x.imageUrl||'')}}
function start(){loadHome();const hf=document.querySelector('.singleton-form');hf.addEventListener('submit',async e=>{e.preventDefault();const b=hf.querySelector('[data-submit]');b.disabled=true;try{const d=data(hf);d.imageUrl=await uploadImage(hf,'home');await setDoc(doc(db,'home','main'),d,{merge:true});hf.elements.imageUrl.value=d.imageUrl||'';preview(hf,d.imageUrl);alert('홈 화면이 저장됐어요!')}catch(err){alert(err.message||'저장 중 오류가 발생했어요.')}finally{b.disabled=false}});
document.querySelectorAll('.content-form').forEach(f=>{f.addEventListener('submit',async e=>{e.preventDefault();const b=f.querySelector('[data-submit]');b.disabled=true;try{const id=f.elements._id.value,d=data(f);if(['wardrobe','instagram'].includes(f.dataset.collection))d.imageUrl=await uploadImage(f,f.dataset.collection);if(id)await updateDoc(doc(db,f.dataset.collection,id),d);else await addDoc(collection(db,f.dataset.collection),{...d,createdAt:serverTimestamp()});reset(f)}catch(err){alert(err.message||'저장 중 오류가 발생했어요.')}finally{b.disabled=false}});f.querySelector('[data-cancel]').addEventListener('click',()=>reset(f))});
['songs','notices','schedules','wardrobe','instagram','curiosity'].forEach(name=>{const el=document.querySelector(`[data-list="${name}"]`);onSnapshot(query(collection(db,name),orderBy('createdAt','desc')),s=>{el.innerHTML=s.empty?'<div class="empty">등록된 내용이 없어요.</div>':s.docs.map(d=>{const x=d.data();return `<div class="manage-row"><div style="display:flex;gap:12px;align-items:center">${x.imageUrl?`<img src="${esc(x.imageUrl)}" style="width:64px;height:64px;object-fit:cover;border-radius:14px">`:''}<div><h3>${esc(x.title||'제목 없음')}${x.artist?' · '+esc(x.artist):''}</h3><p>${esc(x.content||x.date||'')}</p></div></div><div class="mini"><button class="soft" data-edit="${d.id}">수정</button><button class="danger" data-delete="${d.id}">삭제</button></div></div>`}).join('');el.querySelectorAll('[data-delete]').forEach(b=>b.addEventListener('click',async()=>{if(confirm('정말 삭제할까요?'))await deleteDoc(doc(db,name,b.dataset.delete))}));el.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>{const sd=s.docs.find(d=>d.id===b.dataset.edit),x=sd.data(),f=document.querySelector(`form[data-collection="${name}"]`);f.elements._id.value=sd.id;[...f.elements].forEach(e=>{if(!e.name||e.name==='_id'||e.type==='file')return;e.value=e.name==='tags'?(x.tags||[]).join(', '):(x[e.name]??'')});preview(f,x.imageUrl||'');f.querySelector('[data-submit]').textContent='수정 저장';f.querySelector('[data-cancel]').classList.remove('hidden')}))})})}}
